Repository YunoHost-Apps/peertube_ynh, pull requests merged in 2019-06, with the labels that each got.

#91 upgrade to 1.3.0
  README.md
  conf/app.src
  conf/production.yaml
  manifest.json
  scripts/install
Labels: enhancement

#92 Apply example_ynh
  README.md
  manifest.json
  scripts/_common.sh
  scripts/backup
  scripts/install
  scripts/remove
  scripts/restore
  scripts/upgrade
  scripts/ynh_send_readme_to_admin__2
  scripts/ynh_systemd_action
Labels: enhancement

#93 Testing
  README.md
  check_process
  conf/app.src
  conf/production.yaml
  manifest.json
  scripts/_common.sh
  scripts/backup
  scripts/install
  scripts/remove
  scripts/restore
  scripts/upgrade
  scripts/ynh_send_readme_to_admin__2
  scripts/ynh_systemd_action
Labels: enhancement

#94 Add ovh_fix information
  README.md
Labels: enhancement

#96 update readme with ovh command line
  README.md
Labels: enhancement

#98 Testing
  manifest.json
  scripts/install
  scripts/remove
  scripts/restore
  scripts/upgrade
Labels: bug

#99 Testing
  manifest.json
  scripts/install
  scripts/remove
  scripts/restore
  scripts/upgrade
Labels: bug

#104 Upgrade to 1.3.1
  README.md
  conf/app.src
  manifest.json
Labels: enhancement

#105 Testing
  README.md
  check_process
  conf/app.src
  manifest.json
  pull_request_template.md
Labels: enhancement

#106 Testing
  README.md
  check_process
  conf/app.src
  manifest.json
  pull_request_template.md
Labels: enhancement

#108 check upgrade from 1.3.0
  check_process
Labels: bug

#109 fixing message issue and adding node PATH
  conf/message
  conf/message_remove
  scripts/install
  scripts/remove
  scripts/upgrade
Labels: enhancement

#112 Testing
  conf/message
  conf/message_remove
  scripts/install
  scripts/remove
  scripts/upgrade
Labels: bug, enhancement

#113 Testing
  conf/message
  conf/message_remove
  scripts/install
  scripts/remove
  scripts/upgrade
Labels: bug, enhancement
